name: git-utils
version: 0
github: yairchu/git-utils
license: BSD3
author: yairchu

library:
  source-dirs: lib
  dependencies:
  - directory

ghc-options:
- -Wall
- -Wcompat
- -Wredundant-constraints

dependencies:
- base
- extra
- optparse-applicative
- process

executables:
  sub-rebase:
    main: sub-rebase.hs
    dependencies:
    - git-utils
  remerge:
    main: remerge.hs
    dependencies:
    - git-utils
